#!/usr/bin/env node
/**
 * Tier-0 context pack: assembles docs/system-brief.md deterministically from
 * repo state (no LLM). The brief is the "everything an agent needs in ~2k
 * tokens" starting point; the oracle (src/oracle/) is the deeper Tier-1 path.
 * Regenerate with `npm run brief` whenever structure/docs change.
 */
import fs from "fs";
import path from "path";

const ROOT = process.cwd();

function read(p: string): string {
  try {
    return fs.readFileSync(path.join(ROOT, p), "utf-8");
  } catch {
    return "";
  }
}

function listDir(p: string): string[] {
  try {
    return fs.readdirSync(path.join(ROOT, p)).sort();
  } catch {
    return [];
  }
}

function npmScripts(): string {
  const pkg = JSON.parse(read("package.json")) as {
    scripts?: Record<string, string>;
  };
  return Object.entries(pkg.scripts ?? {})
    .map(([name, cmd]) => `| \`npm run ${name}\` | \`${cmd}\` |`)
    .join("\n");
}

function envVars(): string {
  const lines = read(".env.example").split("\n");
  const vars: string[] = [];
  for (const line of lines) {
    const m = line.match(/^#?\s*([A-Z][A-Z0-9_]+)=/);
    if (m) vars.push(m[1]);
  }
  return [...new Set(vars)].map((v) => `\`${v}\``).join(" · ");
}

function moduleMap(): string {
  const rows: string[] = [];
  const describe: Record<string, string> = {
    "src/linkedin": "Playwright session, people search, profile extraction, match confidence, mid-run auth guard",
    "src/github": "REST fetches (ghFetch cache), user/repo collection, graph expansion, identity surface",
    "src/substack": "RSS feed + recommender scrape",
    "src/website": "personal-site scrape; site-discovered GitHub overrides LinkedIn",
    "src/olympiad": "CSV index (IMO/IOI/IPhO/IChO, year ≥ 2020) + search hints",
    "src/pipeline": "orchestration: resolve → expand → merge → score → persist; branch (hop-2) expand",
    "src/scoring": "discovery final_score heuristic",
    "src/storage": "jsonStore (TTL cache, atomic writes), personStore, profileStore",
    "src/assessment": "rubric-driven LLM judges over frozen candidates; priority_score",
    "src/digest": "digest build/render/send (Resend), reviewer feedbackStore",
    "src/oracle": "system-knowledge oracle: BM25 index over docs/code, cited answers, MCP server",
    "src/seeds": "seed parsing ({name, country})",
    server: "Express API :8787 — runs, trees, profiles, assessment, feedback, cancel",
    "web/src": "Vite+React radial-tree UI, profile/assess panels",
    scripts: "CLI entry points (assess, digest, brief, oracle ask)",
    rubrics: "judge rubric YAMLs",
    tests: "vitest suites (assessment, digest, linkedin, oracle, storage, web)",
  };
  for (const [dir, desc] of Object.entries(describe)) {
    if (fs.existsSync(path.join(ROOT, dir))) {
      rows.push(`| \`${dir}/\` | ${desc} |`);
    }
  }
  return rows.join("\n");
}

/** tSearch rows of the vision doc's §4 risk table, if present. */
function riskRows(): string {
  const doc = read("docs/product-vision-and-direction.md");
  const reviewed = doc.match(/\| Last reviewed \| (.+?) \|/)?.[1] ?? "unknown";
  const rows = doc
    .split("\n")
    .filter((l) => /^\| \*\*/.test(l) && /\| tSearch \|/i.test(l))
    .map((l) => {
      const cells = l.split("|").map((c) => c.trim());
      const severity = cells[1]?.replace(/\*\*/g, "");
      const risk = cells[3]?.slice(0, 220);
      return `- **${severity}** — ${risk}${(cells[3]?.length ?? 0) > 220 ? "…" : ""}`;
    });
  return rows.length
    ? `Vision doc last reviewed **${reviewed}** (fresher copies may sit on unmerged \`claude/epic-pasteur*\` branches).\n\n${rows.join("\n")}`
    : "_No risk table found — read docs/product-vision-and-direction.md directly._";
}

function docsIndex(): string {
  return listDir("docs")
    .filter((f) => f.endsWith(".md") && f !== "system-brief.md")
    .map((f) => `\`docs/${f}\``)
    .join(" · ");
}

const brief = `# tSearch — System Brief

> Auto-generated by \`npm run brief\` (\`scripts/generateSystemBrief.ts\`) on ${new Date().toISOString().slice(0, 10)}.
> Do not edit by hand. This is the Tier-0 context pack for agents/humans who
> need working knowledge of the system fast. Deeper answers: the tsearch-oracle
> MCP server (\`src/oracle/\`) or the docs listed at the bottom.

## What it is

Unseen-talent discovery. Olympiad/named seeds are resolved to LinkedIn
identities (headed Playwright + cookies), enriched from personal websites,
expanded one hop through their real GitHub collaboration graph (collaborators,
followers) and Substack, scored on builder/thinker/pedigree evidence, and
inspected on a radial-tree UI. Rubric-driven LLM judges then assess frozen
candidates' public work into a \`priority_score\`, and a recruiter digest is
emailed via Resend with reviewer feedback looping back into ranking.

\`\`\`text
login (cookies) → resolve LinkedIn + websites → expand GitHub/Substack (hop-1)
    → optional hop-2 branch expand (UI) → score → candidates.json + profiles/
    → assessment judges (frozen input) → digest email → reviewer feedback
\`\`\`

## Load-bearing invariants

- **Discovery / assessment separation:** assessment reads frozen
  \`output/candidates.json\` only; never re-runs discovery or fixes identity.
  \`final_score\` (discovery) and \`priority_score\` (assessment) are never
  collapsed into one number. Reviewer feedback reorders digests but never
  rewrites \`priority_score\`.
- **Evidence-grounded judging:** missing evidence maps to
  \`insufficient_public_evidence\`, never a negative judgment; ownership share
  is omitted (not fabricated) when no unfiltered repo commit sample exists.
- **No PII in git:** \`profiles/\`, \`backup/\`, \`data/\`, \`cache/\`,
  \`output/\`, \`cookies.json\`, \`.env\` are gitignored. The repo is public.
- **Fail-closed side effects:** \`digest:send\` defaults to \`--dry-run\`;
  tests/iteration use \`ASSESSMENT_MOCK_LLM=1\`; LinkedIn scraping is paced
  (\`LINKEDIN_DELAY_MS\`), cached, and fails loudly on session expiry
  (\`LinkedInAuthError\`) rather than emitting garbage.

## Module map

| Path | Responsibility |
|------|----------------|
${moduleMap()}

## Commands

| Command | Runs |
|---------|------|
${npmScripts()}

The coding loop: one change → \`npm run typecheck\` → scoped
\`npx vitest run tests/<area>\` → \`npm run verify\` green before commit.
CI (\`.github/workflows/ci.yml\`) enforces the same gate.

## Data stores (all gitignored, filesystem JSON — no database)

- \`output/candidates.json\` — frozen discovery output; assessment's only input
- \`profiles/<seed>/…\` — per-seed tree profiles feeding the UI
- \`data/people/<slug>.json\` — cross-run per-person records (score history, graph, freshness)
- \`data/feedback/<candidate_id>.json\` — reviewer verdicts (relevant / not_relevant / explore_network)
- \`cache/{github,linkedin-search,linkedin-profile-v2,substack}/\` — TTL'd fetch cache (\`FORCE_REFRESH=1\` bypasses once)
- \`output/assessment-runs/<id>/\` — assessment records + digest artifacts

## Environment variables

${envVars()}

## Current risks (from the scheduled triage routine)

${riskRows()}

## Deeper reading

${docsIndex()}
`;

fs.writeFileSync(path.join(ROOT, "docs/system-brief.md"), brief, "utf-8");
console.log(
  `[brief] wrote docs/system-brief.md (${brief.length} chars, ~${Math.round(brief.length / 4)} tokens)`
);
